version: "3"

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    env_file:
      - ./api/.env
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    depends_on:
      - db
    links:
      - db
