CREATE DATABASE IF NOT EXISTS nest_data;
USE nest_data;
CREATE TABLE IF NOT EXISTS user(
    id INT NOT NULL UNIQUE AUTO_INCREMENT, 
    name VARCHAR(20) NOT NULL UNIQUE, 
    age INT, 
    PRIMARY KEY (id)
);